- .github/workflows/android.yml
CICD 알림 노예 주홍이를 세팅했습니다.
android ci script - 웹훅 연결 
juhong:
> CICD알림노예주홍이세팅

- .github/workflows/android.yml
CI Script에 gradle caching 추가
- add gradle caching
> 🔀 :: (#12) - add gradle caching

- build-logic/convention/build.gradle.kts
- build-logic/convention/src/main/java/com/msg/convention/AndroidFeatureConventionPlugin.kt
feature 모듈에서 사용할 플러그인 생성
- Create AndroidFeatureConventionPlugin
> 🔀 :: (#19) - Create FeaturePlugin

- core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/LoginUseCase.kt
- core/model/src/main/java/com/hackathon/model/MyClass.kt
- core/model/src/main/java/com/msg/model/remote/AuthTokenModel.kt
- core/model/src/main/java/com/msg/model/remote/request/LoginRequest.kt
- core/network/build.gradle.kts
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
- core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
- core/network/src/main/java/com/msg/network/exception/HttpException.kt
- core/network/src/main/java/com/msg/network/exception/NeedLoginException.kt
- core/network/src/main/java/com/msg/network/exception/NetworkException.kt
- core/network/src/main/java/com/msg/network/util/BitgoeulApiHandler.kt
login 파트의 통신부분을 세팅합니다
- add AuthAPI
- add AuthDataSource
- add AuthRepository
- add LoginUseCase
- add DataSource, Repository Module
- add NetworkModule
> 🔀 :: (#21) - Set up network on login part

- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/datastore/build.gradle.kts
- core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
- core/datastore/src/main/java/com/msg/datastore/AuthTokenSerializer.kt
- core/datastore/src/main/java/com/msg/datastore/di/DataSourceModule.kt
- core/datastore/src/main/proto/authToken.proto
- core/domain/src/main/java/com/msg/domain/auth/LoginUseCase.kt
- core/domain/src/main/java/com/msg/domain/auth/SaveTokenUseCase.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
Token을 저장, Refresh가능하게 세팅 합니다
- add LocalDataSource
- add saveToken to AuthRepository
- add SaveTokenUseCase
그동안 사용해보지 않았던 protobuf datasource를 사용했습니다.
따라서 아직 살짝 미숙한 부분이 존재할 수 있습니다.
> 🔀 :: (#24) - Save and Refresh Token

- core/network/build.gradle.kts
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
- core/network/src/main/java/com/msg/network/util/AuthInterceptor.kt
- core/network/src/main/java/com/msg/network/util/DateTimeFormatter.kt
Interceptor를 구현합니다
- add AuthInterceptor
- add authInterceptor to OkhttpClient
> 🔀 :: (#23) - Add Interceptor

- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpJobClubTeacher.kt
- core/model/src/main/java/com/msg/model/remote/request/SignUpJobClubTeacherRequest.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
취업 동아리 선생님 회원가입 파트의 통신부분을 세팅합니다.
- add SignUpJobClubTeacherRequest
- add signUpClubTeacher fun in AuthAPI
- add signUpJobClubTeacher fun in AuthDataSource
- add signUpJobClubTeacher in AuthRepository
- add SignUpJobClubTeacherUseCase
> 🔀 :: (#31) - Set up network on job club teacher sign up

- core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
Textfield의 변경사항을 적용합니다.
- apply background color of disabled state
- apply changed color of border with filled state
> 🔀 :: (#33) - Apply changed Textfield

- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpJobClubTeacherUseCase.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpProfessorUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/SignUpProfessorRequest.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
대학 교수 회원가입 파트 통신세팅
- add SignUpProfessorRequest
- add signUpProfessor fun in AuthAPI
- add signUpProfessor fun in AuthDataSource
- add signUpProfessor fun in AuthRepository
- add SignUpProfessorUseCase
> 🔀 :: (#34) - Set up network on professor sign up part

- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpGovernment.kt
- core/model/src/main/java/com/msg/model/remote/request/SignUpGovernmentRequest.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
유관 기관 회원가입 파트 통신 세팅
- add SignUpGovernmentRequest
- add signUpGovernment fun in AuthAPI
- add signUpGovernment fun in AuthDataSource
- add signUpGovernment fun in AuthRepository
- add SignUpGovernmentUseCase
> 🔀 :: (#35) - Set up network on government sign up part

- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpCompanyInstructorUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/SignUpCompanyInstructorRequest.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
기업 강사 회원가입 파트 통신 세팅
- add SignUpCompanyInstructorRequest
- add signUpCompanyInstructor fun in AuthAPI
- add signUpCompanyInstructor fun in DataSource
- add signUpCompanyInstructor fun in AuthRepository
- add SignUpCompanyInstructorUseCase
> 🔀 :: (#36) - Set up network on company instructor sign up part

- core/data/src/main/java/com/msg/data/repository/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/WithdrawUseCase.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
회원탈퇴 파트 통신 세팅
- add withdraw fun on AuthAPI
- add withdraw fun in AuthDataSource
- add withdraw fun in AuthRepository
- add WithdrawUseCase
> 🔀 :: (#42) - Set up network on withdraw part

- core/design-system/src/main/java/com/msg/design_system/component/textfield/BitgoeulTextField.kt
- core/design-system/src/main/java/com/msg/design_system/util/LastPasswordVisibleVisualTransformation.kt
VisualTransformation을 커스텀 하여 password textfield 의 마지막 자리를 볼 수 있게 변경합니다.
- add LastPasswordVisibleVisualTransformation
- apply to PasswordTextField
> 🔀 :: (#46) - Change to see last digit in password textfield

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/msg/bitgoeul_android/BitgoeulApplication.kt
- app/src/main/java/com/msg/bitgoeul_android/MainActivity.kt
- app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
- app/src/main/java/com/msg/bitgoeul_android/navigation/TopLevelDestination.kt
- app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulApp.kt
- app/src/main/java/com/msg/bitgoeul_android/ui/BitgoeulAppState.kt
- feature/login/src/main/java/com/bitgoeul/login/LoginScreen.kt
- feature/login/src/main/java/com/bitgoeul/login/navigation/LoginNavigation.kt
- feature/sign-up/src/main/java/com/msg/sign_up/SignUpScreen.kt
- feature/sign-up/src/main/java/com/msg/sign_up/navigation/SignUpNavigation.kt
SAA를 세팅합니다
- add NavHost
- add AppState
- add BitgoeulApp
> 🔀 :: (#45) - Set up SAA

- core/data/src/main/java/com/msg/data/repository/auth/AuthRepository.kt
- core/data/src/main/java/com/msg/data/repository/auth/AuthRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpBbozzakTeacherUseCase.kt
- core/domain/src/main/java/com/msg/domain/auth/SignUpGovernmentUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/auth/SignUpBbozzakTeacherRequest.kt
- core/network/src/main/java/com/msg/network/api/AuthAPI.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/auth/AuthDataSourceImpl.kt
뽀짝샘 회원가입 파트의 네트워크 세팅
- add SignUpBbozzakTeacher fun in AuthAPI
- add SignUpBbozzakTeacher fun in authDataSource
- add SignUpBbozzakTeacher fun in authRepository
- add SignUpBbozzakTeacherUseCase
> 🔀 :: (#53) - Set up network on bbozzak teacher sign up part

- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/activity/ApproveStudentActivityInfoUseCase.kt
- core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
학생활동정보승인 네트워크 세팅
- add approveStudentActivityInfo fun in ActivityAPI
- add approveStudentActivityInfo fun in ActivityDataSource
- add approveStudentActivityInfo fun in ActivityRepository
- add ApproveStudentActivityInfoUseCase
> 🔀 :: (#69) - Set up network on approve student activity info

- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/activity/InquiryMyStudentActivityInfoListUseCase.kt
- core/model/src/main/java/com/msg/model/remote/enumdatatype/ApproveStatus.kt
- core/model/src/main/java/com/msg/model/remote/model/activity/InquiryStudentActivityModel.kt
- core/model/src/main/java/com/msg/model/remote/response/activity/InquiryStudentActivityListResponse.kt
- core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
학생 자신이 작성한 활동 정보 리스트 조회
- 📝  add ApproveStatus
- 📝  add InquiryStudentActivityListResponse
- 📝  add inquiryMyStudentActivityInfo fun in ActivityAPI
- 📝  add inquiryMyStudentActivityInfoList fun in ActivityDataSource
- 📝  add inquiryMyStudentActivityInfoList fun in ActivityRepository
- 📝  add InquiryMyStudentActivityInfoUseCase
> 🔀 :: (#76) - Set up network on inquiry my student activity info list

- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/activity/InquiryStudentActivityInfoListUseCase.kt
- core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
학생 활동 리스트 조회 네트워크 세팅
- :memo: add inquiryStudentActivityInfoList fun in ActivityAPI
- :memo: add inquiryStudentActivityInfoList fun in ActivityDataSource
- :memo: add inquiryStudentActivityInfoList fun in ActivityRepository
- :memo: add InquiryStudentActivityInfoListUseCase
> 🔀 :: (#78) - Set up network on inquiry activity list

- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/activity/InquiryDetailStudentActivityInfoUseCase.kt
- core/model/src/main/java/com/msg/model/remote/response/activity/InquiryDetailStudentActivityInfoResponse.kt
- core/network/src/main/java/com/msg/network/api/ActivityAPI.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/activity/ActivityDataSourceImpl.kt
학생 활동 정보 상세보기 네트워크 세팅
- :memo: add InquiryDetailStudentActivityInfoResponse
- :memo: add inquiryDetailStudentActivityInfo fun in ActivityAPI
- :memo: add inquiryDetailStudentActivityInfo fun in ActivityDataSource
- :memo: add inquiryDetailStudentActivityInfo fun in ActivityRepository
- :memo: add InquiryDetailStudentActivityInfoUseCase
> 🔀 :: (#82) - Set up inquiry detail student activity info

- core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepository.kt
- core/data/src/main/java/com/msg/data/repository/activity/ActivityRepositoryImpl.kt
- core/data/src/main/java/com/msg/data/repository/user/UserRepository.kt
- core/data/src/main/java/com/msg/data/repository/user/UserRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/activity/ChangePasswordUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/user/ChangePasswordRequest.kt
- core/network/src/main/java/com/msg/network/api/UserAPI.kt
- core/network/src/main/java/com/msg/network/datasource/user/UserDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/user/UserDataSourceImpl.kt
- core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
비밀번호 변경 네트워크 세팅
- :fire: delete useless import
- :memo: add ChangePasswordRequest
- :memo: add changePassword fun in UserAPI
- :memo: add provideUserAPI in NetworkModule
- :memo: add bindUserDataSource in DataSourceModule
- :memo: add changePassword fun in UserDataSource
- :memo: add bindUserRepository in RepositoryModule
- :memo: add changePassword fun in UserRepository
- :memo: add ChangePasswordUseCase
> 🔀 :: (#85) - Set up network on change password

- core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
- core/data/src/main/java/com/msg/data/repository/faq/FaqRepository.kt
- core/data/src/main/java/com/msg/data/repository/faq/FaqRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/faq/AddFrequentlyAskedQuestionUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/faq/AddFrequentlyAskedQuestionsRequest.kt
- core/model/src/main/java/com/msg/model/remote/request/faq/FrequentlyAskedQuestionsRequest.kt
- core/network/src/main/java/com/msg/network/api/FaqAPI.kt
- core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/faq/FaqDataSourceImpl.kt
- core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
자주 묻는 질문 등록 네트워크 세팅
📝 add AddFrequentlyAskedQuestionsRequest
📝 add addFrequentlyAskedQuestions fun in FaqAPI
📝 add provideFaqAPI in NetworkModule
📝 add bindFaqDataSource in DataSourceModule
📝 add addFrequentlyAskedQuestions fun in FaqDataSource
📝 add bindFaqRepository in RepositoryModule
📝 add addFrequentlyAskedQuestions fun in FaqRepository
📝 add AddFrequentlyAskedQuestionUseCase
> 🔀 :: (#70) - Set up network frequently asked questions

- core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
- core/data/src/main/java/com/msg/data/repository/certification/CertificationRepository.kt
- core/data/src/main/java/com/msg/data/repository/certification/CertificationRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/certification/GetDetailCertificationListUseCase.kt
- core/model/src/main/java/com/msg/model/remote/response/certification/DetailCertificationResponse.kt
- core/model/src/main/java/com/msg/model/remote/response/certification/GetDetailCertificationResponse.kt
- core/network/src/main/java/com/msg/network/api/CertificationAPI.kt
- core/network/src/main/java/com/msg/network/api/FaqAPI.kt
- core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
- core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
자격증 리스트 상세 조회 (취업동아리 선생님 Role) API의 Network를 세팅해야함
Certification API Interface getDetailCertificationList 작성
Certification API Interface getDetailCertificationList 함수 작성
CertificationDataSource Interface 작성
CertificationDataSource Interface getDetailCertificationList 함수 작성
CertificationDataSourceImpl 작성
CertificationDataSourceImpl getDetailCertificationList 함수 작성
CertificationRepository Interface getDetailCertificationList 함수작성
CertificationRepositoryImpl getDetailCertificationList 함수 작성
GetDetailCertificationListUseCase 작성
RepositoryModule에 CertificationRepository Bind
NetworkModule에 Certification API Provide
DataSourceModule에 CertificationDataSource Bind
제가 세팅하지 않은 클래스나 인터페이스의 내용이 있다면 알려주세요.
> 🔀 :: (#105) Set Up Get Certification List Role Teacher

- core/data/src/main/java/com/msg/data/repository/certification/CertificationRepository.kt
- core/data/src/main/java/com/msg/data/repository/certification/CertificationRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/certification/WriteCertificationUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/certification/WriteCertificationRequest.kt
- core/network/src/main/java/com/msg/network/api/CertificationAPI.kt
- core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
자격증 작성 API 네트워크 세팅을 해야함
Certification API wrtieCertification 함수 작성
CertificationDataSource wrtieCertification 함수 작성
CertificationRepository wrtieCertification 함수작성
WrtieCertificationUseCase 작성
> 🔀 :: (#115) Set Up Write Certification

- core/data/src/main/java/com/msg/data/repository/certification/CertificationRepository.kt
- core/data/src/main/java/com/msg/data/repository/certification/CertificationRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/certification/EditCertificationUseCase.kt
- core/network/src/main/java/com/msg/network/api/CertificationAPI.kt
- core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/certification/CertificationDataSourceImpl.kt
자격증 수정 API 네트워크 세팅해야함
Certification API editCertification 함수 작성
CertificationDataSource editCertification 함수 작성
CertificationRepository editCertification 함수작성
EditCertificationUseCase 작성
> 🔀 :: (#117) Set Up Edit Certification

- core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
- core/data/src/main/java/com/msg/data/repository/club/ClubRepository.kt
- core/data/src/main/java/com/msg/data/repository/club/ClubRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/club/GetClubListUseCase.kt
- core/model/src/main/java/com/msg/model/remote/response/club/ClubListResponse.kt
- core/network/src/main/java/com/msg/network/api/ClubAPI.kt
- core/network/src/main/java/com/msg/network/datasource/club/ClubDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/club/ClubDataSourceImpl.kt
- core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Club도메인 및 동아리 리스트 조회 API 네트워크를 연결해야함
ClubAPI getClubList 함수 작성
ClubListResponse 데이터 클래스 작성
ClubDataSource getClubList 함수 작성
ClubRepository getClubList 함수 작성
GetClubListUseCase 클래스 작성
RepositoryModule ClubRepository 등록
DatasourceModule ClubDataSource 등록
NetworkModule ClubAPI 등록
제가 잘못 세팅한 부분이 있다면 알려주세요.
> 🔀 :: (#119) Set Up Get Club List

- app/build.gradle.kts
- app/src/main/java/com/msg/bitgoeul_android/navigation/BitgoeulNavHost.kt
- app/src/main/java/com/msg/bitgoeul_android/navigation/TopLevelDestination.kt
- build-logic/convention/src/main/java/com/msg/convention/AndroidFeatureConventionPlugin.kt
- core/datastore/src/main/java/com/msg/datastore/AuthTokenDataSource.kt
- core/design-system/src/main/java/com/msg/design_system/component/dialog/NegativeActionDialog.kt
- core/design-system/src/main/java/com/msg/design_system/component/dialog/PositiveActionDialog.kt
- core/model/src/main/java/com/msg/model/remote/model/activity/StudentActivityModel.kt
- core/ui/src/main/java/com/msg/ui/StudentActivityList.kt
- feature/lecture/src/main/java/com/msg/lecture/LectureDetailScreen.kt
- feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailScreen.kt
- feature/student-activity/src/main/java/com/msg/student_activity/ActivityDetailSettingScreen.kt
- feature/student-activity/src/main/java/com/msg/student_activity/AddActivityScreen.kt
- feature/student-activity/src/main/java/com/msg/student_activity/StudentActivityScreen.kt
- feature/student-activity/src/main/java/com/msg/student_activity/StudentActivityViewModel.kt
- feature/student-activity/src/main/java/com/msg/student_activity/navigation/StudentActivityNavigation.kt
- feature/student-activity/src/main/java/com/msg/student_activity/util/Event.kt
- feature/student-activity/src/main/java/com/msg/student_activity/util/errorHandling.kt
학생활동 파트의 기능을 구현합니다
- add viewModel
- add Navigation
- some changes in dialog
> 🔀 :: (#111) - Student activity feature implement

- core/data/src/main/java/com/msg/data/repository/club/ClubRepository.kt
- core/data/src/main/java/com/msg/data/repository/club/ClubRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/club/GetClubDetailUseCase.kt
- core/model/src/main/java/com/msg/model/remote/response/club/ClubDetailResponse.kt
- core/network/src/main/java/com/msg/network/api/ClubAPI.kt
- core/network/src/main/java/com/msg/network/datasource/club/ClubDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/club/ClubDataSourceImpl.kt
동아리 상세 조회 API 네트워크를 연결해야함
ClubAPI getClubDetail 함수 작성
ClubDetailResponse 데이터 클래스 작성
ClubDataSource getClubDetail 함수 작성
ClubRepository getClubDetail 함수 작성
GetClubDetailUseCase 클래스 작성
> 🔀 :: (#122) Set Up Get Detail Club

- core/data/src/main/java/com/msg/data/repository/user/UserRepository.kt
- core/data/src/main/java/com/msg/data/repository/user/UserRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/user/ChangePasswordUseCase.kt
- core/domain/src/main/java/com/msg/domain/user/InquiryMyPageUseCase.kt
- core/model/src/main/java/com/msg/model/remote/response/user/InquiryMyPageResponse.kt
- core/network/src/main/java/com/msg/network/api/UserAPI.kt
- core/network/src/main/java/com/msg/network/datasource/user/UserDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/user/UserDataSourceImpl.kt
마이페이지 조회 네트워크 세팅
- :memo: add InquiryMyPageResponse
- :memo: add inquiryMaPage fun in UserAPI
- :memo: add inquiryMyPage fun in UserDataSource
- :memo: add inquiryMyPage fun in UserRepository
- :memo: add InquiryMyPageUseCase, ChangePasswordUseCase
> 🔀 :: (#128) - Set up network on inquiry my page

- core/data/src/main/java/com/msg/data/di/RepositoryModule.kt
- core/data/src/main/java/com/msg/data/repository/admin/AdminRepository.kt
- core/data/src/main/java/com/msg/data/repository/admin/AdminRepositoryImpl.kt
- core/domain/src/main/java/com/msg/domain/admin/GetUserListUseCase.kt
- core/model/src/main/java/com/msg/model/remote/request/admin/GetUserListRequest.kt
- core/model/src/main/java/com/msg/model/remote/response/admin/UseListContentResponse.kt
- core/model/src/main/java/com/msg/model/remote/response/admin/UseListResponse.kt
- core/model/src/main/java/com/msg/model/remote/response/admin/UserListResponse.kt
- core/network/src/main/java/com/msg/network/api/AdminAPI.kt
- core/network/src/main/java/com/msg/network/datasource/admin/AdminDataSource.kt
- core/network/src/main/java/com/msg/network/datasource/admin/AdminDataSourceImpl.kt
- core/network/src/main/java/com/msg/network/di/DataSourceModule.kt
- core/network/src/main/java/com/msg/network/di/NetworkModule.kt
Admin 도메인과의 유저 리스트 조회 API를 네트워크 세팅해야함
AdminAPI Interface 작성
AdminAPI Interface getUserList 함수 작성
AdminDataSource 작성
AdminDataSource getUserList 함수 작성
AdminDataSourceImpl 작성
AdminDataSourceImpl getUserList 함수 작성
AdminRepository Interface getUserList 함수작성
AdminRepositoryImpl getUserList 함수 작성
GetUserListUseCase 작성
RepositoryModule에 AdminRepository Bind
NetworkModule에 AdminAPI Provide
DataSourceModule에 AdminDataSource Bind
> 🔀 :: (#132) Set Up Get User List

- core/model/src/main/java/com/msg/model/remote/enumdatatype/Division.kt
- core/model/src/main/java/com/msg/model/remote/enumdatatype/Semester.kt
장학사님과의 면담이후 EnumClass가 추가되었음
새로운 EnumClass들을 생성 및 작성
```kotlin
// Semester Enum Class
enum class Semester {
FIRST_YEAR_FALL_SEMESTER,
SECOND_YEAR_SPRING_SEMESTER,
SECOND_YEAR_FALL_SEMESTER,
THIRD_YEAR_SPRING_SEMESTER
}
```
```kotlin
// Division Enum Class
enum class Division {
AUTOMOBILE_INDUSTRY,
ENERGY_INDUSTRY,
MEDICAL_HEALTHCARE,
AI_CONVERGENCE_AI,
CULTURAL_INDUSTRY
}
```
없음
제가 잘못작성한 부분이 있다면 알려주세요.
> 🔀 :: (#152) 새로운 EnumClass 적용
